spring.application.name=salary-backend
spring.datasource.url=jdbc:sqlite:salary_db.db
spring.datasource.driver-class-name=org.xerial.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}